import { readFileSync, readdirSync, writeFileSync } from "node:fs";
const base = new URL("../migrations/", import.meta.url);
const files = readdirSync(base)
  .filter((f) => f.endsWith(".sql") && f !== "0013_user_accounts.sql")
  .sort();
writeFileSync(
  new URL("../src/workspace-schema.js", import.meta.url),
  "// Generated by scripts/workspace-schema.mjs; do not edit.\nexport const migrations = " +
    JSON.stringify(
      files.map((name) => ({
        name,
        sql: readFileSync(new URL(name, base), "utf8"),
      })),
      null,
      2,
    ) +
    ";\n",
);
