-- Normalize once on ingestion, rather than repeatedly scanning accented descriptions.
ALTER TABLE jobs ADD COLUMN search_normalized TEXT;
UPDATE jobs SET search_normalized=replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(lower(COALESCE(COALESCE(title,'') || ' ' || COALESCE(company,'') || ' ' || COALESCE(location,'') || ' ' || COALESCE(description,''),'')),'á','a'),'à','a'),'â','a'),'ã','a'),'ä','a'),'Á','a'),'À','a'),'Â','a'),'Ã','a'),'Ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'É','e'),'È','e'),'Ê','e'),'Ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'Í','i'),'Ì','i'),'Î','i'),'Ï','i'),'ó','o'),'ò','o'),'ô','o'),'õ','o'),'ö','o'),'Ó','o'),'Ò','o'),'Ô','o'),'Õ','o'),'Ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'Ú','u'),'Ù','u'),'Û','u'),'Ü','u'),'ç','c'),'Ç','c');
CREATE TRIGGER jobs_search_insert AFTER INSERT ON jobs BEGIN
UPDATE jobs SET search_normalized=replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(lower(COALESCE(COALESCE(NEW.title,'') || ' ' || COALESCE(NEW.company,'') || ' ' || COALESCE(NEW.location,'') || ' ' || COALESCE(NEW.description,''),'')),'á','a'),'à','a'),'â','a'),'ã','a'),'ä','a'),'Á','a'),'À','a'),'Â','a'),'Ã','a'),'Ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'É','e'),'È','e'),'Ê','e'),'Ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'Í','i'),'Ì','i'),'Î','i'),'Ï','i'),'ó','o'),'ò','o'),'ô','o'),'õ','o'),'ö','o'),'Ó','o'),'Ò','o'),'Ô','o'),'Õ','o'),'Ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'Ú','u'),'Ù','u'),'Û','u'),'Ü','u'),'ç','c'),'Ç','c') WHERE id=NEW.id;
END;
CREATE TRIGGER jobs_search_update AFTER UPDATE OF title,company,location,description ON jobs BEGIN
UPDATE jobs SET search_normalized=replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(lower(COALESCE(COALESCE(NEW.title,'') || ' ' || COALESCE(NEW.company,'') || ' ' || COALESCE(NEW.location,'') || ' ' || COALESCE(NEW.description,''),'')),'á','a'),'à','a'),'â','a'),'ã','a'),'ä','a'),'Á','a'),'À','a'),'Â','a'),'Ã','a'),'Ä','a'),'é','e'),'è','e'),'ê','e'),'ë','e'),'É','e'),'È','e'),'Ê','e'),'Ë','e'),'í','i'),'ì','i'),'î','i'),'ï','i'),'Í','i'),'Ì','i'),'Î','i'),'Ï','i'),'ó','o'),'ò','o'),'ô','o'),'õ','o'),'ö','o'),'Ó','o'),'Ò','o'),'Ô','o'),'Õ','o'),'Ö','o'),'ú','u'),'ù','u'),'û','u'),'ü','u'),'Ú','u'),'Ù','u'),'Û','u'),'Ü','u'),'ç','c'),'Ç','c') WHERE id=NEW.id;
END;
